Решение задач по pandas и numpy

In [ ]:
import pandas as pd
import numpy as np

100 задач по Pandas

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

1.5.3


In [ ]:
pd.show_versions()


/usr/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")



INSTALLED VERSIONS
------------------
commit           : 2e218d10984e9919f0296931d92ea851c6a6faf5
python           : 3.10.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.15.109+
Version          : #1 SMP Fri Jun 9 10:57:30 UTC 2023
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.5.3
numpy            : 1.23.5
pytz             : 2023.3.post1
dateutil         : 2.8.2
setuptools       : 67.7.2
pip              : 23.1.2
Cython           : 3.0.2
pytest           : 7.4.1
hypothesis       : None
sphinx           : 5.0.2
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.9.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.7
jinja2           : 3.1.2
IPython          : 7.34.0
pandas_datareader: 0.10.0
bs4              : 4.11.2
bottleneck       : None
brotli   

In [ ]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

In [ ]:
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
df=pd.DataFrame(data, index=labels)

In [ ]:
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 700.0+ bytes


In [ ]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [ ]:
df.iloc[:3]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [ ]:
df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [ ]:
df.iloc[[3,4,8]][['animal','age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [ ]:
df.query('visits>=3')

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [ ]:
df[df['visits']>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [ ]:
df[df['age'].isnull()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [ ]:
df[(df['animal']=='cat') & (df['age']<3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [ ]:
df[df['age'].between(2,4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [ ]:
df.loc['f', 'age']=1.5

In [ ]:
df['visits'].sum()

19

In [ ]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

In [1]:
df.loc['k']=['dog','5.5', 2, 'no']

NameError: ignored

In [ ]:
df['animal'].value_counts()

dog      5
cat      4
snake    2
Name: animal, dtype: int64

In [ ]:
df.sort_values(by=['age','visits'], ascending=[False, True])

animal  age visits priority
k    dog  5.5      2       no
i    dog  7.0      2    False
e    dog  5.0      2    False
g  snake  4.5      1    False
j    dog  3.0      1    False
b    cat  3.0      3     True
a    cat  2.5      1     True
f    cat  1.5      3    False
c  snake  0.5      2    False
h    cat  NaN      1     True
d    dog  NaN      3     True

In [ ]:
df['priority']=df['priority'].map({'yes':True, 'no':False})

In [ ]:
df['animal'].replace('snake', 'python')

a       cat
b       cat
c    python
d       dog
e       dog
f       cat
g    python
h       cat
i       dog
j       dog
k       dog
Name: animal, dtype: object

In [ ]:
table=pd.pivot_table(df, index='animal', values='age', columns='visits', aggfunc='mean')
table

<ipython-input-246-7dd0b25b6218>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  df.pivot_table(index='animal', columns='visits', values='age', aggfunc='mean')


animal  age visits priority
a    cat  2.5      1      NaN
b    cat  3.0      3      NaN
c  snake  0.5      2      NaN
d    dog  NaN      3      NaN
e    dog  5.0      2      NaN
f    cat  1.5      3      NaN
g  snake  4.5      1      NaN
h    cat  NaN      1      NaN
i    dog  7.0      2      NaN
j    dog  3.0      1      NaN
k    dog  5.5      2    False

In [ ]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})

In [ ]:
df.drop_duplicates(subset='A')

A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

In [ ]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df.sub(df.mean(axis=1), axis=0)


0         1         2
0  0.363112 -0.281461 -0.081651
1 -0.027371 -0.286472  0.313843
2 -0.052536  0.370787 -0.318250
3  0.207155 -0.012069 -0.195086
4  0.016710 -0.100481  0.083771

In [ ]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
df.sum().idxmin()

'h'

In [ ]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
df.drop_duplicates(keep=False)

0  1  2
3  1  0  0
4  1  1  1
9  1  0  1

In [ ]:
df.drop_duplicates(keep=False)

0  1  2
3  0  1  1

In [ ]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)
(df.isnull().cumsum(axis=1) == 3).idxmax(axis=1)

0    e
1    c
2    d
3    h
4    d
dtype: object

In [ ]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
df['rank']= df.groupby('grps')['vals'].rank(method='dense', ascending=False)
df.sort_values(by=['grps', 'vals'], ascending=[True, False])
new_df=df[df['rank'].between(1,3)]
new_df.groupby('grps')['vals'].sum()

grps
a    409
b    156
c    345
Name: vals, dtype: int64

In [ ]:
 df.groupby('grps')['vals'].nlargest(3).sum(level=0)

<ipython-input-44-1437a4c44fc3>:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  df.groupby('grps')['vals'].nlargest(3).sum(level=0)


grps
a    409
b    156
c    345
Name: vals, dtype: int64

In [ ]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])
df.sort_values(by=['A']).head(30)

A   B
40   1  40
47   1  83
35   2  13
33   5  59
5    8  54
43   8  72
46   8  86
62   9  43
24   9  71
61   9  18
92   9  96
48  11  35
50  14  17
36  15  53
79  18  50
28  19  94
90  19  32
38  19  54
88  20  25
11  21  68
75  22  97
8   24  20
6   24  64
68  29  43
56  29  23
23  32  61
3   33  43
82  35  36
16  37  60
32  38  96

In [ ]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])
df.groupby(pd.cut(df['A'], np.arange(0, 101, 10)))['B'].sum()


A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int64

In [ ]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
df['Y'] = df.groupby((df['X'] == 0).cumsum()).cumcount()
first_zero_idx = (df['X'] == 0).idxmax()
first_zero_idx
df['Y'].iloc[0:first_zero_idx] += 1
df

X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

In [ ]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
df.unstack().sort_values()[-3:].index.tolist()


[(5, 7), (6, 4), (2, 5)]

In [ ]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
df

vals grps
0    -12    A
1     -7    B
2    -14    A
3      4    A
4     -7    A
5     28    B
6     -2    A
7     -1    A
8      8    A
9     -2    B
10    28    A
11    12    A
12    16    A
13   -24    A
14   -12    A

In [ ]:
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15),
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})

def replace(group):
    mask = group<0
    group[mask] = group[~mask].mean()
    return group

df.groupby(['grps'])['vals'].transform(replace)

In [ ]:
df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
g1=df.groupby(['group'])['value']
g2=df.fillna(0).groupby(['group'])['value']
s=g2.rolling(3, min_periods=1).sum()/g1.rolling(3,min_periods=1).count()
s.reset_index(level=0, drop=True).sort_index()

0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
Name: value, dtype: float64

In [ ]:
dti = pd.date_range(start='2015-01-01', end='2015-12-31', freq='B')
s = pd.Series(np.random.rand(len(dti)), index=dti)
s

2015-01-01    0.467392
2015-01-02    0.002838
2015-01-05    0.566368
2015-01-06    0.455653
2015-01-07    0.579007
                ...   
2015-12-25    0.491645
2015-12-28    0.449268
2015-12-29    0.641410
2015-12-30    0.480072
2015-12-31    0.716957
Freq: B, Length: 261, dtype: float64

In [ ]:
s[s.index.weekday == 2].sum()


28.33226858307842

In [ ]:
s.resample('M').mean()


2015-01-31    0.487459
2015-02-28    0.473349
2015-03-31    0.505426
2015-04-30    0.410577
2015-05-31    0.426325
2015-06-30    0.497145
2015-07-31    0.513423
2015-08-31    0.528836
2015-09-30    0.514046
2015-10-31    0.582712
2015-11-30    0.504009
2015-12-31    0.529275
Freq: M, dtype: float64

In [ ]:
s.groupby(pd.Grouper(freq='4M')).idxmax()


2015-01-31   2015-01-28
2015-05-31   2015-03-03
2015-09-30   2015-06-03
2016-01-31   2015-11-05
Freq: 4M, dtype: datetime64[ns]

In [ ]:
pd.date_range('2015-01-01', '2016-12-31', freq='WOM-3THU')

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq='WOM-3THU')

In [ ]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

In [ ]:
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)



In [ ]:
temp=df.From_To.str.split('_', expand=True)
temp.columns = ['From', 'To']
temp

From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

In [ ]:
temp['From']=temp['From'].str.capitalize()
temp['To']=temp['To'].str.capitalize()
temp


From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

In [ ]:
df=pd.concat([temp, df], axis=1)
test

From         To  FlightNumber  RecentDelays              Airline
0    London      Paris       10045.0      [23, 47]               KLM(!)
1    Madrid      Milan           NaN            []    <Air France> (12)
2    London  Stockholm       10065.0  [24, 43, 87]  (British Airways. )
3  Budapest      Paris           NaN          [13]       12. Air France
4  Brussels     London       10085.0      [67, 32]          "Swiss Air"

In [ ]:
df['Airline']=df['Airline'].str.extract('([a-zA-Z\s]+)', expand=False).str.strip()

In [ ]:
df

From         To  FlightNumber  RecentDelays          Airline
0    London      Paris       10045.0      [23, 47]              KLM
1    Madrid      Milan           NaN            []       Air France
2    London  Stockholm       10065.0  [24, 43, 87]  British Airways
3  Budapest      Paris           NaN          [13]       Air France
4  Brussels     London       10085.0      [67, 32]        Swiss Air

In [ ]:
delays=df['RecentDelays'].apply(pd.Series)
delays.columns=['delay_{}'.format(n) for n in range(1, len(delays.columns)+1)]
df=df.drop('RecentDelays', axis=1).join(delays)
df

<ipython-input-97-006de2cd3019>:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  delays=df['RecentDelays'].apply(pd.Series)


From         To  FlightNumber          Airline  delay_1  delay_2  \
0    London      Paris       10045.0              KLM     23.0     47.0   
1    Madrid      Milan           NaN       Air France      NaN      NaN   
2    London  Stockholm       10065.0  British Airways     24.0     43.0   
3  Budapest      Paris           NaN       Air France     13.0      NaN   
4  Brussels     London       10085.0        Swiss Air     67.0     32.0   

   delay_3  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN

In [ ]:
letters = ['A', 'B', 'C']
numbers = list(range(10))

mi = pd.MultiIndex.from_product([letters, numbers])
s = pd.Series(np.random.rand(30), index=mi)
s

A  0    0.107905
   1    0.377278
   2    0.411064
   3    0.914482
   4    0.827265
   5    0.706511
   6    0.543754
   7    0.927669
   8    0.834811
   9    0.151059
B  0    0.022432
   1    0.528292
   2    0.007323
   3    0.087980
   4    0.063313
   5    0.160930
   6    0.945132
   7    0.003232
   8    0.755115
   9    0.829098
C  0    0.634961
   1    0.475535
   2    0.409318
   3    0.877396
   4    0.951136
   5    0.853100
   6    0.646634
   7    0.735633
   8    0.560199
   9    0.604359
dtype: float64

In [ ]:
s.index.is_lexsorted()


<ipython-input-99-08970af1a121>:1: FutureWarning: MultiIndex.is_lexsorted is deprecated as a public function, users should use MultiIndex.is_monotonic_increasing instead.
  s.index.is_lexsorted()


True

In [ ]:
s.loc[:, [1, 3, 6]]


A  1    0.377278
   3    0.914482
   6    0.543754
B  1    0.528292
   3    0.087980
   6    0.945132
C  1    0.475535
   3    0.877396
   6    0.646634
dtype: float64

In [ ]:
s.loc[pd.IndexSlice[:'B', 5:]]


A  5    0.706511
   6    0.543754
   7    0.927669
   8    0.834811
   9    0.151059
B  5    0.160930
   6    0.945132
   7    0.003232
   8    0.755115
   9    0.829098
dtype: float64

Numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [ ]:
Z=np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
Z[4]=1

In [ ]:
Z=np.arange(10, 50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
Z=np.arange(9).reshape(3,3)
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
Z=np.array([1,2,0,0,4,0])
nz=np.nonzero(Z)
nz

(array([0, 1, 4]),)

In [ ]:
Z=np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Z=np.random.randint(low=0, high=3, size=(3,3,3))
Z

array([[[2, 2, 0],
        [1, 2, 1],
        [0, 2, 0]],

       [[0, 0, 1],
        [2, 0, 1],
        [2, 1, 2]],

       [[2, 2, 2],
        [0, 0, 0],
        [2, 2, 1]]])

In [ ]:
Z = np.random.random(size=(10,10))
Zmin, Zmax=Z.min(), Z.max()

In [ ]:
Z=np.random.random(30)
m=Z.mean()

In [ ]:
Z=np.ones((10,10))
Z[1:-1, 1:-1]=0

In [ ]:
Z = np.ones((5,5))
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0

In [ ]:
Z

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({'x_1':[1, 2, 2, 4, 5, 6], 'y_1' : [1, 3, 2, 1, 3, 3]})
df2 = pd.DataFrame({'x_2':[1, 1, 2, 2, 4], 'y_2' : [1, 5, 5, 2, 4]})



In [ ]:
df1

x_1  y_1
0    1    1
1    2    3
2    2    2
3    4    1
4    5    3
5    6    3

In [ ]:
df2

x_2  y_2
0    1    1
1    1    5
2    2    5
3    2    2
4    4    4